### ISSUE TITLE
Docs for Herokuapp & Glitch

### ISSUE THREAD

**Issue by TheaQueen** [TheBastionBot/BastionBotDocs#6]
I m seeing a lot of users are asking for help with herokuapp & glitch.com so if we can have docs for it, it l be very helpful for them.

**Comment by k3rn31p4nic** [comment]
Heroku uses an ephemeral file system, which is an issue for Bastion because the database will get reset every 24 hours, or thereabouts.
Glitch on the other hand, doesn't support `ffmpeg` (from what I've observed from users), which is a bummer considering most users self host because they want music and Bastion can't play music without `ffmpeg`.

That's the main reason whey we don't officially support these platforms and don't have guide for it.

**Comment by TheaQueen** [comment]
we can mention these in the docs beforehand so users can be aware of these issues and proceed if they still want to. but having them is useful so that the support team dont have to guide them again and again.

**Comment by k3rn31p4nic** [comment]
Yeah, right. Would you like to open a PR?

**Comment by TheaQueen** [comment]
i can only write the docs for herokuapp. i ve never used glitch so ive to try it before i can write the docs for it

**Comment by k3rn31p4nic** [comment]
Heroku docs are done: https://github.com/TheBastionBot/BastionBotDocs/pull/7

This issue will be closed once docs for Glitch are written.

**Comment by k3rn31p4nic** [comment]
Closed in https://github.com/TheBastionBot/BastionBotDocs/commit/36e4aa95736e07f9cde9ed0669e405c2c45d8339
